# Generated by Django 6.0.5 on 2026-05-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('personnel', 'Personnel'), ('admin', 'Admin')], default='reporter', max_length=20),
        ),
    ]
