# Generated by Django 6.0.5 on 2026-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_units_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('resolve', 'Resolve'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
    ]
