# Generated by Django 6.0.5 on 2026-05-06 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to='core.incident'),
        ),
        migrations.AddField(
            model_name='units',
            name='eta',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('standby', 'Standby'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('investigating', 'Investigating'), ('returning', 'Returning')], default='standby', max_length=20),
        ),
        migrations.AddField(
            model_name='units',
            name='unit_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('security', 'Security'), ('accident', 'Accident')], default='medical', max_length=20),
        ),
        migrations.CreateModel(
            name='UnitResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.incident')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.units')),
            ],
        ),
    ]
