# Generated by Django 6.0.5 on 2026-05-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_units_assignment_units_eta_units_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='_school_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='operator_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
