# Generated by Django 6.0.5 on 2026-05-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_incident__school_id_incident_operator_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='specific_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('fire', 'Fire'), ('med', 'Medical'), ('sec', 'Security'), ('accident', 'Accident')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dispatched', 'Dispatched'), ('onscene', 'On Scene'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
