# Generated by Django 6.0.5 on 2026-05-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='sector',
        ),
    ]
