# Generated by Django 6.0.5 on 2026-05-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_incident_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('admin', 'Admin')], default='reporter', max_length=20),
        ),
        migrations.DeleteModel(
            name='UnitResponse',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
