# Generated by Django 6.0.5 on 2026-05-07 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_units_assignment_remove_user_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_id',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='core_notifi_is_read_57d3f5_idx'), models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx')],
            },
        ),
    ]
