# Generated by Django 6.0.5 on 2026-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_incident_incident_id_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['incident'], name='core_notifi_inciden_9ba6b6_idx'),
        ),
    ]
