# Generated by Django 6.0.5 on 2026-05-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_notification_incident_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('resolve', 'Resolve'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
    ]
