# Generated by Django 6.0.5 on 2026-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_is_verified_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(default=23439, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
