# Generated by Django 6.0.5 on 2026-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_id',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dispatched', 'Dispatched'), ('onscene', 'On Scene'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
