# Generated by Django 5.2.8 on 2026-09-21 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_school_id_user_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
